<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     itemOperations={
 *          "get",
 *          "delete"
 *     },
 *     collectionOperations={
 *          "get",
 *          "post"={"denormalization"={"groups"={"component:write"}}}
 *     }
 * )
 * @ApiFilter(PropertyFilter::class, arguments={"parameterName": "props" })
 * @ApiFilter(SearchFilter::class, properties={"id": "exact", "product.id": "exact"})
 *
 * @ORM\Entity(repositoryClass="App\Repository\ProductComponentRepository")
 * @ORM\Table(
 *    uniqueConstraints={
 *        @ORM\UniqueConstraint(name="product_component_uniq", columns={"product_id", "component_id"})
 *    }
 * )
 * @ORM\Table(name="factorio_product_component")
 */
class ProductComponent
{
    /**
     * An autogenerated unique ID for the product component
     *
     * @var UuidInterface $id
     *
     * @ORM\Id()
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     */
    private $id;

    /**
     * The quantity of the product needed
     *
     * @var int
     * @ORM\Column(type="integer")
     *
     * @Groups({"component:write"})
     */
    private $quantity = 1;

    /**
     * The product
     *
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", cascade={"persist"})
     * @ORM\JoinColumn(name="product_id", referencedColumnName="id")
     *
     * @ApiProperty(writableLink=true)
     * @Groups({"component:write"})
     */
    private $product;

    /**
     * The component
     *
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Product", cascade={"persist"})
     * @ORM\JoinColumn(name="component_id", referencedColumnName="id")
     *
     * @ApiProperty(writableLink=true)
     * @Groups({"component:write"})
     */
    private $component;

    public function getId(): ?UuidInterface
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }


    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getComponent(): ?Product
    {
        return $this->component;
    }

    public function setComponent(?Product $component): self
    {
        $this->component = $component;

        return $this;
    }
}
